spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

magazine:
  app:
    jwtRefreshCookieName: magazine-jwt-refresh
    jwtSecret: magazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKey
    accessTokenSecret: AccessTokenmagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKey
    accessTokenExpirationMs: 1000000
    jwtRefreshExpirationMs: 180000000