spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magazine
    username: postgres
    password: Mal.asiye3
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 5MB
magazine:
  app:
    jwtRefreshCookieName: magazine-jwt-refresh
    jwtSecret: magazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKey
    accessTokenSecret: AccessTokenmagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKeymagazineSecretKey
    accessTokenExpirationMs: 1000000
    jwtRefreshExpirationMs: 180000000